apiVersion: v1
version: 0.1.6
appVersion: 0.5
description: A Helm chart for a highly available postfix relay in Kubernetes
name: postfix
keywords:
- postfix
sources:
- https://github.com/howismyboat/postfix-relay-kubernetes
maintainers:
- name: Andrew Kent
  email: andrew@howismyboat.com
